// On-chain ID verification helpers.
// Both listingId and offerId are generated by the contract and emitted in events.
// The service reads them back from the frontend (which captured them from on-chain).
// These helpers confirm the IDs exist on-chain by scanning recent event logs.

import { bargoEscrowAbi } from '@bargo/shared';
import type { Address, ListingId, OfferId } from '@bargo/shared';

type ChainClient = ReturnType<typeof import('./read.js').createChainClient>;

// Look back at most 50 blocks (covers ~10 min at 12s block time).
const LOOKBACK_BLOCKS = 50n;

/**
 * Verify a listingId exists on-chain by checking for a ListingCreated event.
 * Returns the seller address, or throws with code 'onchain-listing-not-found'.
 */
export async function verifyListingOnChain(
  client: ChainClient,
  escrowAddress: `0x${string}`,
  listingId: ListingId,
): Promise<{ seller: Address }> {
  const latestBlock = await client.getBlockNumber();
  const fromBlock = latestBlock > LOOKBACK_BLOCKS ? latestBlock - LOOKBACK_BLOCKS : 0n;

  const logs = await client.getContractEvents({
    address: escrowAddress,
    abi: bargoEscrowAbi,
    eventName: 'ListingCreated',
    args: { listingId },
    fromBlock,
  });

  if (logs.length === 0) {
    const err = new Error(
      `ListingCreated event not found for listingId=${listingId} in last ${LOOKBACK_BLOCKS} blocks`,
    );
    (err as NodeJS.ErrnoException).code = 'onchain-listing-not-found';
    throw err;
  }

  const seller = logs[0]?.args?.seller;
  if (!seller) throw new Error('ListingCreated event missing seller field');
  return { seller: seller as Address };
}

/**
 * Verify an offerId exists on-chain by checking for an OfferSubmitted event.
 * Returns the buyer address, or throws with code 'onchain-offer-not-found'.
 */
export async function verifyOfferOnChain(
  client: ChainClient,
  escrowAddress: `0x${string}`,
  offerId: OfferId,
): Promise<{ buyer: Address }> {
  const latestBlock = await client.getBlockNumber();
  const fromBlock = latestBlock > LOOKBACK_BLOCKS ? latestBlock - LOOKBACK_BLOCKS : 0n;

  const logs = await client.getContractEvents({
    address: escrowAddress,
    abi: bargoEscrowAbi,
    eventName: 'OfferSubmitted',
    args: { offerId },
    fromBlock,
  });

  if (logs.length === 0) {
    const err = new Error(
      `OfferSubmitted event not found for offerId=${offerId} in last ${LOOKBACK_BLOCKS} blocks`,
    );
    (err as NodeJS.ErrnoException).code = 'onchain-offer-not-found';
    throw err;
  }

  const buyer = logs[0]?.args?.buyer;
  if (!buyer) throw new Error('OfferSubmitted event missing buyer field');
  return { buyer: buyer as Address };
}
